require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PaidsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Paid. As you add validations to Paid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaidsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all paids as @paids" do
      paid = Paid.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:paids)).to eq([paid])
    end
  end

  describe "GET show" do
    it "assigns the requested paid as @paid" do
      paid = Paid.create! valid_attributes
      get :show, {:id => paid.to_param}, valid_session
      expect(assigns(:paid)).to eq(paid)
    end
  end

  describe "GET new" do
    it "assigns a new paid as @paid" do
      get :new, {}, valid_session
      expect(assigns(:paid)).to be_a_new(Paid)
    end
  end

  describe "GET edit" do
    it "assigns the requested paid as @paid" do
      paid = Paid.create! valid_attributes
      get :edit, {:id => paid.to_param}, valid_session
      expect(assigns(:paid)).to eq(paid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Paid" do
        expect {
          post :create, {:paid => valid_attributes}, valid_session
        }.to change(Paid, :count).by(1)
      end

      it "assigns a newly created paid as @paid" do
        post :create, {:paid => valid_attributes}, valid_session
        expect(assigns(:paid)).to be_a(Paid)
        expect(assigns(:paid)).to be_persisted
      end

      it "redirects to the created paid" do
        post :create, {:paid => valid_attributes}, valid_session
        expect(response).to redirect_to(Paid.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paid as @paid" do
        post :create, {:paid => invalid_attributes}, valid_session
        expect(assigns(:paid)).to be_a_new(Paid)
      end

      it "re-renders the 'new' template" do
        post :create, {:paid => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested paid" do
        paid = Paid.create! valid_attributes
        put :update, {:id => paid.to_param, :paid => new_attributes}, valid_session
        paid.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested paid as @paid" do
        paid = Paid.create! valid_attributes
        put :update, {:id => paid.to_param, :paid => valid_attributes}, valid_session
        expect(assigns(:paid)).to eq(paid)
      end

      it "redirects to the paid" do
        paid = Paid.create! valid_attributes
        put :update, {:id => paid.to_param, :paid => valid_attributes}, valid_session
        expect(response).to redirect_to(paid)
      end
    end

    describe "with invalid params" do
      it "assigns the paid as @paid" do
        paid = Paid.create! valid_attributes
        put :update, {:id => paid.to_param, :paid => invalid_attributes}, valid_session
        expect(assigns(:paid)).to eq(paid)
      end

      it "re-renders the 'edit' template" do
        paid = Paid.create! valid_attributes
        put :update, {:id => paid.to_param, :paid => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paid" do
      paid = Paid.create! valid_attributes
      expect {
        delete :destroy, {:id => paid.to_param}, valid_session
      }.to change(Paid, :count).by(-1)
    end

    it "redirects to the paids list" do
      paid = Paid.create! valid_attributes
      delete :destroy, {:id => paid.to_param}, valid_session
      expect(response).to redirect_to(paids_url)
    end
  end

end
